/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthedChannelsIndexRouteImport } from './routes/_authed/channels/index'
import { Route as AuthedChannelsIdRouteImport } from './routes/_authed/channels/$id'
import { Route as AuthedChannelsAtmeRouteRouteImport } from './routes/_authed/channels/@me/route'
import { Route as AuthedChannelsAtmeIndexRouteImport } from './routes/_authed/channels/@me/index'
import { Route as AuthedChannelsAtmeUuidRouteImport } from './routes/_authed/channels/@me/$uuid'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthedChannelsIndexRoute = AuthedChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedChannelsIdRoute = AuthedChannelsIdRouteImport.update({
  id: '/channels/$id',
  path: '/channels/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedChannelsAtmeRouteRoute = AuthedChannelsAtmeRouteRouteImport.update({
  id: '/channels/@me',
  path: '/channels/@me',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedChannelsAtmeIndexRoute = AuthedChannelsAtmeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedChannelsAtmeRouteRoute,
} as any)
const AuthedChannelsAtmeUuidRoute = AuthedChannelsAtmeUuidRouteImport.update({
  id: '/$uuid',
  path: '/$uuid',
  getParentRoute: () => AuthedChannelsAtmeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/channels/@me': typeof AuthedChannelsAtmeRouteRouteWithChildren
  '/channels/$id': typeof AuthedChannelsIdRoute
  '/channels': typeof AuthedChannelsIndexRoute
  '/channels/@me/$uuid': typeof AuthedChannelsAtmeUuidRoute
  '/channels/@me/': typeof AuthedChannelsAtmeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/channels/$id': typeof AuthedChannelsIdRoute
  '/channels': typeof AuthedChannelsIndexRoute
  '/channels/@me/$uuid': typeof AuthedChannelsAtmeUuidRoute
  '/channels/@me': typeof AuthedChannelsAtmeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_authed/channels/@me': typeof AuthedChannelsAtmeRouteRouteWithChildren
  '/_authed/channels/$id': typeof AuthedChannelsIdRoute
  '/_authed/channels/': typeof AuthedChannelsIndexRoute
  '/_authed/channels/@me/$uuid': typeof AuthedChannelsAtmeUuidRoute
  '/_authed/channels/@me/': typeof AuthedChannelsAtmeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/channels/@me'
    | '/channels/$id'
    | '/channels'
    | '/channels/@me/$uuid'
    | '/channels/@me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/channels/$id'
    | '/channels'
    | '/channels/@me/$uuid'
    | '/channels/@me'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authed'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authed/channels/@me'
    | '/_authed/channels/$id'
    | '/_authed/channels/'
    | '/_authed/channels/@me/$uuid'
    | '/_authed/channels/@me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authed/channels/': {
      id: '/_authed/channels/'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthedChannelsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/channels/$id': {
      id: '/_authed/channels/$id'
      path: '/channels/$id'
      fullPath: '/channels/$id'
      preLoaderRoute: typeof AuthedChannelsIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/channels/@me': {
      id: '/_authed/channels/@me'
      path: '/channels/@me'
      fullPath: '/channels/@me'
      preLoaderRoute: typeof AuthedChannelsAtmeRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/channels/@me/': {
      id: '/_authed/channels/@me/'
      path: '/'
      fullPath: '/channels/@me/'
      preLoaderRoute: typeof AuthedChannelsAtmeIndexRouteImport
      parentRoute: typeof AuthedChannelsAtmeRouteRoute
    }
    '/_authed/channels/@me/$uuid': {
      id: '/_authed/channels/@me/$uuid'
      path: '/$uuid'
      fullPath: '/channels/@me/$uuid'
      preLoaderRoute: typeof AuthedChannelsAtmeUuidRouteImport
      parentRoute: typeof AuthedChannelsAtmeRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthedChannelsAtmeRouteRouteChildren {
  AuthedChannelsAtmeUuidRoute: typeof AuthedChannelsAtmeUuidRoute
  AuthedChannelsAtmeIndexRoute: typeof AuthedChannelsAtmeIndexRoute
}

const AuthedChannelsAtmeRouteRouteChildren: AuthedChannelsAtmeRouteRouteChildren =
  {
    AuthedChannelsAtmeUuidRoute: AuthedChannelsAtmeUuidRoute,
    AuthedChannelsAtmeIndexRoute: AuthedChannelsAtmeIndexRoute,
  }

const AuthedChannelsAtmeRouteRouteWithChildren =
  AuthedChannelsAtmeRouteRoute._addFileChildren(
    AuthedChannelsAtmeRouteRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedChannelsAtmeRouteRoute: typeof AuthedChannelsAtmeRouteRouteWithChildren
  AuthedChannelsIdRoute: typeof AuthedChannelsIdRoute
  AuthedChannelsIndexRoute: typeof AuthedChannelsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedChannelsAtmeRouteRoute: AuthedChannelsAtmeRouteRouteWithChildren,
  AuthedChannelsIdRoute: AuthedChannelsIdRoute,
  AuthedChannelsIndexRoute: AuthedChannelsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
